[programs.localnet]
ido_pool = "7TZqAhcqsPHoZ7sDAeUpDj5woKDDFMYGuX1bgoBsfGPv"

[programs.devnet]
ido_pool = "7TZqAhcqsPHoZ7sDAeUpDj5woKDDFMYGuX1bgoBsfGPv"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "mocha -t 20000 tests/ido-pool.js"
